apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  labels:
    app.kubernetes.io/part-of: tjwa
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
    apps.tanzu.vmware.com/workload-type: server
  name: tjwa.my-apps.tap.20240418184125.0.0+build.6db88c7
spec:
  refName: tjwa.my-apps.tap
  version: 20240418184125.0.0+build.6db88c7
  releaseNotes: |
    Release v20240418184125.0.0+build.6db88c7 of package tjwa.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: shepherd28bcba54c87ddf358ff3d770.azurecr.io/tap-install/workloads/tjwa-my-apps-bundle@sha256:83e7d8e4390899f2f37585d2549a1740e06950aa4a65ed8ba210f45718cf3f7f
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          title: Workload name
          type: string
          default: ""
        replicas:
          title: Replicas
          type: integer
          default: 1
        port:
          title: Port
          type: integer
          default: 8080
        hostname:
          title: Hostname
          type: string
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          default: tap-ingress-selfsigned
        http_route:
          type: object
          additionalProperties: false
          nullable: true
          properties:
            gateways:
              type: array
              items:
                type: object
                additionalProperties: false
                properties:
                  protocol:
                    type: string
                    default: ""
                  name:
                    type: string
                    default: ""
              default:
              - protocol: https
                name: default-gateway

